#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/lybspwm/sxhkd/sxhkdrc &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           6 #12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/lybspwm/launch &

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a lylight state=floating
bspc rule -a lyaudio state=floating
bspc rule -a lyaudiomute state=floating
bspc rule -a lystart state=floating
bspc rule -a Fsearch state=floating
bspc rule -a Osmo state=floating
